# Generated by Django 6.0.4 on 2026-04-27 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("author", models.CharField(db_index=True, max_length=255)),
                (
                    "isbn",
                    models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
                ),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fiction", "Fiction"),
                            ("Science", "Science"),
                            ("History", "History"),
                            ("Technology", "Technology"),
                            ("Biography", "Biography"),
                            ("Philosophy", "Philosophy"),
                            ("Art", "Art"),
                            ("Children", "Children"),
                            ("Reference", "Reference"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("N", "N"),
                            ("O", "O"),
                            ("P", "P"),
                            ("Q", "Q"),
                            ("R", "R"),
                            ("S", "S"),
                            ("T", "T"),
                            ("U", "U"),
                            ("V", "V"),
                            ("W", "W"),
                            ("X", "X"),
                            ("Y", "Y"),
                            ("Z", "Z"),
                        ],
                        db_index=True,
                        help_text="A-Z classification, auto-filled from the title when blank.",
                        max_length=1,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                ("total_stock", models.PositiveIntegerField(default=1)),
                ("available_stock", models.PositiveIntegerField(default=1)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("publisher", models.CharField(blank=True, max_length=160)),
                ("ebook_url", models.URLField(blank=True)),
                ("ebook_provider_label", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title", "author"],
                "indexes": [
                    models.Index(
                        fields=["title", "author"], name="catalog_boo_title_b62bd9_idx"
                    ),
                    models.Index(
                        fields=["genre", "category"],
                        name="catalog_boo_genre_3198b6_idx",
                    ),
                ],
            },
        ),
    ]
