# Generated by Django 6.0.4 on 2026-05-11 04:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="digital_copy_format",
            field=models.CharField(blank=True, default="Web", max_length=40),
        ),
        migrations.AddField(
            model_name="book",
            name="external_cover_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Fiction", "Fiction"),
                    ("Science Fiction", "Science Fiction"),
                    ("Computer Science", "Computer Science"),
                    ("Science", "Science"),
                    ("History", "History"),
                    ("Technology", "Technology"),
                    ("Biography", "Biography"),
                    ("Philosophy", "Philosophy"),
                    ("Art", "Art"),
                    ("Children", "Children"),
                    ("Reference", "Reference"),
                    ("Other", "Other"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book"), name="unique_review_per_book_user"
                    )
                ],
            },
        ),
    ]
