# Generated by Django 6.0.4 on 2026-05-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("REQUEST", "Request"),
                    ("RETURN", "Return"),
                    ("FINE", "Fine"),
                    ("PAYMENT", "Payment"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("QR_UPI", "QR / UPI"),
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("WAIVER", "Waiver"),
                        ],
                        default="QR_UPI",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("WAIVED", "Waived"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("upi_id", models.CharField(default="bookly@upi", max_length=120)),
                ("reference", models.CharField(max_length=80, unique=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "borrow_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="circulation.borrowrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="circulation_user_id_230acb_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="circulation_referen_ba7b01_idx"
                    ),
                ],
            },
        ),
    ]
